import { Orders, User } from "../types";

export const testUser: User = {
  session_id: "00000000-0000-0000-0000-000000000000",
  name: "Ilias",
  loginAt: new Date("2026-01-01T10:00:00").getTime(),
};

export const testOrders: Orders = {
  timestamp: new Date("2026-01-01T10:30:00"),
  all: {
    totalOrders: 4,
    totalPrice: 49.74,
    couponAmount: 1.5,
    deliveryCost: 3,
    totalTips: 2,
    platforms: { web: 2, android: 1, ios: 1 },
    paymentMethods: { cash: 2, credit_card: 1, paypal: 1 },
    firstOrder: "2024-12-31 21:15:00",
    lastOrder: "2025-04-15 13:00:00",
    restaurantWithMostMoneySpent: {
      id: 1,
      name: "Gyro House",
      totalPrice: 35,
      orders: 2,
      longitude: 23.72,
      latitude: 37.98,
      logo: "gyro.png",
      is_open: true,
      is_favorite: true,
      address: "Main 1, Athens",
    },
    restaurants: [
      {
        id: 1,
        name: "Gyro House",
        totalPrice: 35,
        orders: 2,
        longitude: 23.72,
        latitude: 37.98,
        logo: "gyro.png",
        is_open: true,
        is_favorite: true,
        address: "Main 1, Athens",
      },
    ],
    mostOrderedProduct: {
      name: "Pasta",
      quantity: 3,
      totalPrice: 9.99,
      image: "pasta.jpg",
    },
    averageDeliveryTime: 38,
    uniqueRestaurants: 3,
    weekdays: { "Δευτέρα": 1, "Τρίτη": 2 },
    phases: { night: 1, morning: 1, noon: 1, afternoon: 0 },
    months: { "Μάρτιος": 1, "Απρίλιος": 1, "Δεκέμβριος": 1 },
    cities: { Athens: 2, Patras: 1 },
  },
  perYear: [
    {
      year: "2025",
      totalOrders: 2,
      totalPrice: 32.75,
      couponAmount: 1,
      deliveryCost: 2,
      totalTips: 2,
      platforms: { web: 1, android: 1 },
      paymentMethods: { cash: 1, credit_card: 1 },
      firstOrder: "2025-03-10 11:30:00",
      lastOrder: "2025-04-15 13:00:00",
      restaurantWithMostMoneySpent: {
        id: 1,
        name: "Gyro House",
        totalPrice: 35,
        orders: 2,
        longitude: 23.72,
        latitude: 37.98,
        logo: "gyro.png",
        is_open: true,
        is_favorite: true,
        address: "Main 1, Athens",
      },
      restaurants: [],
      mostOrderedProduct: {
        name: "Pita",
        quantity: 2,
        totalPrice: 10,
        image: "pita.jpg",
      },
      averageDeliveryTime: 30,
      uniqueRestaurants: 1,
      weekdays: { "Δευτέρα": 1, "Τρίτη": 1 },
      phases: { morning: 1, noon: 1, afternoon: 0, night: 0 },
      months: { "Μάρτιος": 1, "Απρίλιος": 1 },
      cities: { Athens: 1, Koukaki: 1 },
    },
    {
      year: "2024",
      totalOrders: 1,
      totalPrice: 9.99,
      couponAmount: 0.5,
      deliveryCost: 1,
      totalTips: 0,
      platforms: { web: 0, ios: 1 },
      paymentMethods: { paypal: 1 },
      firstOrder: "2024-12-31 21:15:00",
      lastOrder: "2024-12-31 21:15:00",
      restaurantWithMostMoneySpent: {
        id: 2,
        name: "Pasta Place",
        totalPrice: 9.99,
        orders: 1,
        longitude: 21.73,
        latitude: 38.25,
        logo: "pasta.png",
        is_open: true,
        is_favorite: false,
        address: "Port 2, Patras",
      },
      restaurants: [],
      mostOrderedProduct: {
        name: "Pasta",
        quantity: 3,
        totalPrice: 9.99,
        image: "pasta.jpg",
      },
      averageDeliveryTime: 45,
      uniqueRestaurants: 1,
      weekdays: { "Τρίτη": 1 },
      phases: { night: 1, morning: 0, noon: 0, afternoon: 0 },
      months: { "Δεκέμβριος": 1 },
      cities: { Patras: 1 },
    },
  ],
};
